// Generated by ReScript, PLEASE EDIT WITH CARE


function calculateLogarithmicZoom(currentZoom, deltaY, sensitivityOpt, param) {
  var sensitivity = sensitivityOpt !== undefined ? sensitivityOpt : 1.0;
  var logZoom = Math.log(currentZoom);
  var zoomSpeed = sensitivity * 0.1;
  var newLogZoom = logZoom - deltaY * zoomSpeed * 0.01;
  var newZoom = Math.exp(newLogZoom);
  var adaptiveSensitivity = 1.0 / (1.0 + currentZoom * 0.1);
  return currentZoom + (newZoom - currentZoom) * adaptiveSensitivity;
}

function calculateZoomFactorFromDelta(deltaY, currentZoom, sensitivityOpt, param) {
  var sensitivity = sensitivityOpt !== undefined ? sensitivityOpt : 1.0;
  var baseZoomFactor = deltaY > 0.0 ? 0.85 + currentZoom * 0.02 : 1.15 - currentZoom * 0.02;
  if (deltaY > 0.0) {
    return 1.0 - (1.0 - baseZoomFactor) * sensitivity;
  } else {
    return 1.0 + (baseZoomFactor - 1.0) * sensitivity;
  }
}

function getZoomSensitivity(ctrlKey, shiftKey) {
  if (ctrlKey) {
    return 0.3;
  } else if (shiftKey) {
    return 2.0;
  } else {
    return 1.0;
  }
}

function calculateViewportOffsetForCurrentFrameZoom(currentFrame, currentZoom, newZoom, currentViewportOffset, maxSceneWidth, totalFrames, timelineMarginLeft) {
  if (totalFrames <= 0 || maxSceneWidth <= 0.0 || currentZoom <= 0.0 || newZoom <= 0.0) {
    return currentViewportOffset;
  }
  var basePixelRatio = maxSceneWidth / totalFrames;
  var oldFrameToPxRatio = basePixelRatio * currentZoom;
  var newFrameToPxRatio = basePixelRatio * newZoom;
  var currentFrameScreenX = currentFrame * oldFrameToPxRatio + timelineMarginLeft - currentViewportOffset;
  var newViewportOffset = currentFrame * newFrameToPxRatio + timelineMarginLeft - currentFrameScreenX;
  if (isNaN(newViewportOffset)) {
    return currentViewportOffset;
  }
  var totalContentWidth = totalFrames * newFrameToPxRatio;
  var maxOffset = Math.max(0.0, totalContentWidth - maxSceneWidth);
  var minBound = -maxSceneWidth * 0.1;
  var maxBound = maxOffset + maxSceneWidth * 0.1;
  return Math.max(minBound, Math.min(newViewportOffset, maxBound));
}

export {
  calculateLogarithmicZoom ,
  calculateZoomFactorFromDelta ,
  getZoomSensitivity ,
  calculateViewportOffsetForCurrentFrameZoom ,
  
}
/* No side effect */
