// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function useCanvasScale(elementRef, size) {
  React.useEffect((function () {
          Belt_Option.forEach(Caml_option.nullable_to_opt(elementRef.current), (function (canvasElement) {
                  var ctx = canvasElement.getContext("2d");
                  canvasElement.height = Math.floor(size.scaledHeight) | 0;
                  canvasElement.width = Math.floor(size.scaledWidth) | 0;
                  ctx.scale(size.scale, size.scale);
                  
                }));
          
        }), [size]);
  
}

function calculateTimelineMargins(viewportOffset, videoTotalWidth, visibleWidth) {
  var atVideoStart = viewportOffset <= 0.0;
  var atVideoEnd = viewportOffset + visibleWidth >= videoTotalWidth;
  var leftMargin;
  if (atVideoStart) {
    var visibleStartPortion = Math.min(32.0, -viewportOffset + 32.0);
    leftMargin = Math.max(0.0, visibleStartPortion) | 0;
  } else {
    leftMargin = 0;
  }
  var rightMargin;
  if (atVideoEnd) {
    var pastEndPortion = viewportOffset + visibleWidth - videoTotalWidth;
    var visibleEndPortion = Math.min(32.0, pastEndPortion + 32.0);
    rightMargin = Math.max(0.0, visibleEndPortion) | 0;
  } else {
    rightMargin = 0;
  }
  return [
          leftMargin,
          rightMargin
        ];
}

function calculateTimelineMargin(viewportOffset, videoTotalWidth, visibleWidth) {
  return calculateTimelineMargins(viewportOffset, videoTotalWidth, visibleWidth)[0];
}

function frameToX(frame, size) {
  return frame * size.frameToPxRatio + size.timelineMarginLeft - size.viewportOffset;
}

var audio_height = 60;

var Canvas;

var Canvas2d;

export {
  audio_height ,
  Canvas ,
  Canvas2d ,
  useCanvasScale ,
  calculateTimelineMargins ,
  calculateTimelineMargin ,
  frameToX ,
  
}
/* react Not a pure module */
