// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as CanvasSize from "./canvasSize.bs.js";
import * as EditorContext from "../../EditorContext.bs.js";
import * as SeekBarCanvas from "./SeekBarCanvas.bs.js";
import * as ControlsCanvas from "./ControlsCanvas.bs.js";
import * as SceneMapCanvas from "./SceneMapCanvas.bs.js";

function Timeline(Props) {
  var sectionSize = Props.sectionSize;
  var editorContext = EditorContext.useEditorContext(undefined);
  var match = Curry._1(editorContext.usePlayer, undefined);
  var dispatch = match[1];
  var player = match[0];
  var size = React.useMemo((function () {
          var scale = window.devicePixelRatio;
          var initialBasePxRatio = sectionSize.width / editorContext.videoMeta.durationInFrames;
          var initialVideoTotalWidth = editorContext.videoMeta.durationInFrames * (initialBasePxRatio * player.zoom);
          var match = CanvasSize.calculateTimelineMargins(player.viewportOffset, initialVideoTotalWidth, sectionSize.width);
          var timelineMarginRight = match[1];
          var timelineMarginLeft = match[0];
          var availableWidth = sectionSize.width - timelineMarginLeft - timelineMarginRight;
          var basePxRatio = availableWidth / editorContext.videoMeta.durationInFrames;
          var frameToPxRatio = basePxRatio * player.zoom;
          return {
                  width: sectionSize.width,
                  height: sectionSize.height,
                  scale: scale,
                  scaledWidth: sectionSize.width * scale,
                  scaledHeight: sectionSize.height * scale,
                  maxSceneWidth: availableWidth,
                  frameToPxRatio: frameToPxRatio,
                  pxToFrameRatio: 1 / frameToPxRatio,
                  viewportOffset: player.viewportOffset,
                  timelineMarginLeft: timelineMarginLeft,
                  timelineMarginRight: timelineMarginRight
                };
        }), [
        sectionSize.height,
        sectionSize.width,
        sectionSize.scale,
        editorContext.videoMeta.durationInFrames,
        player.zoom,
        player.viewportOffset
      ]);
  React.useEffect((function () {
          if (player.playState === /* Playing */0) {
            var currentSize_width = size.width;
            var currentSize_height = size.height;
            var currentSize_scale = size.scale;
            var currentSize_scaledWidth = size.scaledWidth;
            var currentSize_scaledHeight = size.scaledHeight;
            var currentSize_maxSceneWidth = size.maxSceneWidth;
            var currentSize_frameToPxRatio = size.frameToPxRatio;
            var currentSize_pxToFrameRatio = size.pxToFrameRatio;
            var currentSize_viewportOffset = player.viewportOffset;
            var currentSize_timelineMarginLeft = size.timelineMarginLeft;
            var currentSize_timelineMarginRight = size.timelineMarginRight;
            var currentSize = {
              width: currentSize_width,
              height: currentSize_height,
              scale: currentSize_scale,
              scaledWidth: currentSize_scaledWidth,
              scaledHeight: currentSize_scaledHeight,
              maxSceneWidth: currentSize_maxSceneWidth,
              frameToPxRatio: currentSize_frameToPxRatio,
              pxToFrameRatio: currentSize_pxToFrameRatio,
              viewportOffset: currentSize_viewportOffset,
              timelineMarginLeft: currentSize_timelineMarginLeft,
              timelineMarginRight: currentSize_timelineMarginRight
            };
            var currentFrameX = CanvasSize.frameToX(player.frame, currentSize);
            if (currentFrameX < 0.0 || currentFrameX > currentSize_maxSceneWidth) {
              var totalContentWidth = editorContext.videoMeta.durationInFrames * currentSize_frameToPxRatio;
              var maxOffset = totalContentWidth > currentSize_maxSceneWidth ? totalContentWidth - currentSize_maxSceneWidth : 0.0;
              var framePosition = player.frame * currentSize_frameToPxRatio;
              var constrainedOffset = framePosition < 0.0 ? 0.0 : (
                  framePosition > maxOffset ? maxOffset : framePosition
                );
              Curry._1(dispatch, {
                    TAG: /* SetViewportOffset */4,
                    _0: constrainedOffset
                  });
            }
            
          }
          
        }), [
        player.frame,
        player.playState,
        player.zoom
      ]);
  var match$1 = player.playState;
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "relative"
                }, match$1 >= 3 ? null : React.createElement(SceneMapCanvas.make, {
                        size: size
                      }), React.createElement(ControlsCanvas.make, {
                      size: size
                    }), React.createElement(SeekBarCanvas.make, {
                      size: size
                    })));
}

var make = Timeline;

export {
  make ,
  
}
/* react Not a pure module */
