// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as CanvasSize from "./canvasSize.bs.js";
import * as EditorContext from "../../EditorContext.bs.js";

function useViewportFollow(sectionSize) {
  var editorContext = EditorContext.useEditorContext(undefined);
  var match = Curry._1(editorContext.usePlayer, undefined);
  var dispatch = match[1];
  var player = match[0];
  return React.useCallback((function (targetFrame) {
                var initialBasePxRatio = sectionSize.width / editorContext.videoMeta.durationInFrames;
                var initialVideoTotalWidth = editorContext.videoMeta.durationInFrames * (initialBasePxRatio * player.zoom);
                var match = CanvasSize.calculateTimelineMargins(player.viewportOffset, initialVideoTotalWidth, sectionSize.width);
                var availableWidth = sectionSize.width - match[0] - match[1];
                var basePxRatio = availableWidth / editorContext.videoMeta.durationInFrames;
                var frameToPxRatio = basePxRatio * player.zoom;
                var totalContentWidth = editorContext.videoMeta.durationInFrames * frameToPxRatio;
                var maxOffset = totalContentWidth > availableWidth ? totalContentWidth - availableWidth : 0.0;
                var framePosition = targetFrame * frameToPxRatio;
                var constrainedOffset = framePosition < 0.0 ? 0.0 : (
                    framePosition > maxOffset ? maxOffset : framePosition
                  );
                return Curry._1(dispatch, {
                            TAG: /* SetViewportOffset */4,
                            _0: constrainedOffset
                          });
              }), [
              player.viewportOffset,
              player.zoom
            ]);
}

export {
  useViewportFollow ,
  
}
/* react Not a pure module */
