// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Hooks from "../../hooks/Hooks.bs.js";
import * as React from "react";
import * as ZoomUtils from "../../utils/ZoomUtils.bs.js";
import * as EditorContext from "../../EditorContext.bs.js";

function ZoomControls(Props) {
  var editorContext = EditorContext.useEditorContext(undefined);
  var match = Curry._1(editorContext.usePlayer, undefined);
  var dispatch = match[1];
  var player = match[0];
  var handleZoomIn = Hooks.useEvent(function (param) {
        var zoomFactor = ZoomUtils.calculateZoomFactorFromDelta(-1.0, player.zoom, 1.0, undefined);
        var newZoom = player.zoom * zoomFactor;
        return Curry._1(dispatch, {
                    TAG: /* SetZoom */3,
                    _0: newZoom
                  });
      });
  var handleZoomOut = Hooks.useEvent(function (param) {
        var zoomFactor = ZoomUtils.calculateZoomFactorFromDelta(1.0, player.zoom, 1.0, undefined);
        var newZoom = player.zoom * zoomFactor;
        if (newZoom <= 1.0) {
          return Curry._1(dispatch, {
                      TAG: /* BatchZoomUpdate */5,
                      _0: newZoom,
                      _1: 0.0
                    });
        } else {
          return Curry._1(dispatch, {
                      TAG: /* SetZoom */3,
                      _0: newZoom
                    });
        }
      });
  var handleZoomReset = Hooks.useEvent(function (param) {
        return Curry._1(dispatch, {
                    TAG: /* BatchZoomUpdate */5,
                    _0: 1,
                    _1: 0.0
                  });
      });
  return React.createElement("div", {
              className: "flex gap-2"
            }, React.createElement("button", {
                  className: "text-white hover:bg-gray-700 rounded px-2 py-1 text-sm",
                  title: "Zoom Out (Ctrl+wheel for fine)",
                  onClick: handleZoomOut
                }, "-"), React.createElement("button", {
                  className: "text-white hover:bg-gray-700 rounded px-2 py-1 text-xs font-mono",
                  title: "Reset Zoom (Fit to timeline)",
                  onClick: handleZoomReset
                }, (player.zoom * 100.0).toFixed(0) + "%"), React.createElement("button", {
                  className: "text-white hover:bg-gray-700 rounded px-2 py-1 text-sm",
                  title: "Zoom In (Shift+wheel for coarse)",
                  onClick: handleZoomIn
                }, "+"));
}

var make = ZoomControls;

export {
  make ,
  
}
/* Hooks Not a pure module */
